services:
  - type: worker
    name: kingbird-pdf-bot
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "20"
